### ISSUE TITLE
Unexpcted token `('

### ISSUE THREAD

**Issue by nicedevil007** [MrKrisKrisu/netcup-api#4]
Hi I try to use your repo to get something done with the api of netcup

unfortunately I always end up with the error message of the title after typing in this:

```api=new API($apiKey, $apiPassword, $customerId);```

ofc those variables are filled with the right ones in quotes or doublequotes (none of them works). Can you help me out with this?

**Comment by MrKrisKrisu** [comment]
Do you have the full error message/stack trace?

**Comment by nicedevil007** [comment]
![image](https://github.com/user-attachments/assets/f8a3577e-2554-4aaf-8e8f-4e1ebc4fcf5c)

something like this?

**Comment by MrKrisKrisu** [comment]
Seems like you are missing an `$` before the `api` variable.
